# Generated by Django 4.1.7 on 2023-02-25 08:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobsPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('job_type', models.CharField(max_length=120)),
                ('skills', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('is_remote', models.BooleanField(default=False)),
                ('description', ckeditor.fields.RichTextField()),
                ('company_name', models.CharField(blank=True, max_length=164)),
                ('website', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobsPortal.baseuser', verbose_name='User')),
            ],
        ),
    ]
